<script lang="ts">
	import {
		Paragraph,
		Card,
		Fields,
		Field,
		TableContainer,
		Table,
		Sheet,
		SheetMasthead,
		SheetParties,
		SheetParty,
		SheetMeta,
		SheetMetaRow,
		SheetTotals,
		SheetTotalRow,
		SheetNotes,
		SheetFooter,
		SheetSignatures,
		SheetSign,
		SheetLegal,
		SheetPageno,
		SheetPrintButton
	} from '@keenmate/svelte-pure-admin';
</script>

<Paragraph>
	<code>&lt;Sheet&gt;</code> is a printable A4 "paper" document shell for invoices, orders, quotes and receipts.
	It composes the framework's other blocks — line items use <code>&lt;TableContainer&gt;</code> +
	<code>&lt;Table&gt;</code>, reg/VAT pairs use <code>&lt;Fields&gt;</code> — and adds the invoice-shaped regions
	(masthead, parties, meta, totals, notes, footer). <code>&lt;SheetPrintButton&gt;</code> prints a single sheet in
	isolation via the core print helper.
</Paragraph>

<Card titleText="Invoice" hasPadding={false} bodyClass="p-4">
	<Sheet id="inv-142" isFramed>
		<SheetMasthead isRuled doctitle="INVOICE No. 2026-0142" docmeta="Tax invoice">
			Twin Peaks Ltd.
		</SheetMasthead>

		<SheetParties>
			<SheetParty label="Supplier" name="Twin Peaks Ltd." variant="boxed">
				251 Fir Avenue<br />Twin Peaks, 98065
				<Fields isHorizontal isCompact hasBorder={false} class="mt-2">
					<Field labelText="Reg. No." valueText="12345678" />
					<Field labelText="VAT No." valueText="GB12345678" />
				</Fields>
			</SheetParty>
			<SheetParty label="Bill to" name="Great Northern Hotel Ltd." variant="strong">
				1 Riverside Drive<br />Snoqualmie, 98065
			</SheetParty>
		</SheetParties>

		<SheetMeta isBoxed>
			<SheetMetaRow label="Reference No.">2071845390</SheetMetaRow>
			<SheetMetaRow label="Issue date">Sep 9, 2026</SheetMetaRow>
			<SheetMetaRow label="Due date">Sep 23, 2026</SheetMetaRow>
			<SheetMetaRow label="Payment method">Bank transfer</SheetMetaRow>
		</SheetMeta>

		<TableContainer>
			<Table isBordered>
				<thead>
					<tr>
						<th>Description</th>
						<th class="text-end">Qty</th>
						<th class="text-end">Unit price</th>
						<th class="text-end">Amount</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<span class="pa-table__item-title">Application support</span>
							<span class="pa-table__item-desc">Business portal — August 2026</span>
						</td>
						<td class="text-end">5 days</td>
						<td class="text-end">8,000.00</td>
						<td class="text-end">40,000.00</td>
					</tr>
					<tr>
						<td>
							<span class="pa-table__item-title">Application support</span>
							<span class="pa-table__item-desc">Business portal — September 2026</span>
						</td>
						<td class="text-end">5 days</td>
						<td class="text-end">8,000.00</td>
						<td class="text-end">40,000.00</td>
					</tr>
				</tbody>
			</Table>
		</TableContainer>

		<SheetTotals>
			<SheetTotalRow label="Subtotal">80,000.00</SheetTotalRow>
			<SheetTotalRow label="VAT (0%)">0.00</SheetTotalRow>
			<SheetTotalRow label="Total due" isGrand>€80,000.00</SheetTotalRow>
		</SheetTotals>

		<SheetNotes>
			<p>
				Please note that if the due date is not met, we will charge interest on late payment at the
				statutory rate. Thank you for your business.
			</p>
		</SheetNotes>

		<SheetFooter>
			<SheetSignatures>
				<SheetSign label="Issued by" />
				<SheetSign label="Received by" />
				<SheetSign label="Stamp" />
			</SheetSignatures>
			<SheetLegal>
				Registered in the Commercial Register, Section C, File 12345 · Generated by an accounting
				&amp; invoicing system.
			</SheetLegal>
			<SheetPageno>1 / 1</SheetPageno>
		</SheetFooter>

		<div class="mt-4 text-end" data-print-omit>
			<SheetPrintButton title="Invoice 2026-0142">Print this invoice</SheetPrintButton>
		</div>
	</Sheet>
</Card>

<Card titleText="Payment reminder — three-party header">
	<Sheet isFramed>
		<SheetMasthead doctitle="Payment Reminder">Blue Rose Telecom Ltd.</SheetMasthead>

		<SheetParties cols={3}>
			<SheetParty label="Customer service" name="Blue Rose Telecom Ltd.">
				100 Bureau Plaza<br />Philadelphia, 19106
			</SheetParty>
			<SheetParty label="Customer" name="Twin Peaks Ltd.">
				251 Fir Avenue<br />Twin Peaks, 98065
			</SheetParty>
			<SheetParty label="Contact address" name="Dale Cooper">
				251 Fir Avenue<br />Twin Peaks, 98065
			</SheetParty>
		</SheetParties>

		<SheetNotes>
			<p>
				Dear Sir or Madam, unfortunately we have not yet received your payment for services. We kindly
				ask you to settle it at your earliest convenience.
			</p>
		</SheetNotes>
	</Sheet>
</Card>
