<script lang="ts">
	/**
	 * Pure Admin Document Component (Svelte 5)
	 * Based on @keenmate/pure-admin-core snippets/document.html
	 *
	 * Word-style hierarchical, auto-numbered sections. Nest <DocumentSection>
	 * inside one another and the outline number (1, 1.1, 1.1.1 …) is generated by
	 * CSS counters — you never write it, so reordering or inserting a section
	 * renumbers everything automatically (up to six levels). Put body copy in
	 * <DocumentText>. Set `isManual` to author your own numbers (appendices, A / A.1).
	 */

	type DocumentDensity = 'compact' | 'spacious';

	interface Props {
		/** Author-written numbers (`pa-document--manual`); the CSS auto-number is disabled —
		 *  supply each number via `number` on <DocumentSection>. */
		isManual?: boolean;
		/** Vertical rhythm between sections (`pa-document--compact` / `--spacious`). */
		density?: DocumentDensity;
		/** Drop the per-level indentation (`pa-document--flush`); the number chain conveys hierarchy. */
		isFlush?: boolean;
		/** Additional CSS classes */
		class?: string;
		/** Section content: <DocumentSection> blocks. */
		children?: import('svelte').Snippet;
	}

	let { isManual = false, density, isFlush = false, class: className = '', children }: Props = $props();

	const classes = $derived(() => {
		const base = ['pa-document'];
		if (isManual) base.push('pa-document--manual');
		if (density) base.push(`pa-document--${density}`);
		if (isFlush) base.push('pa-document--flush');
		if (className) base.push(className);
		return base.join(' ');
	});
</script>

<div class={classes()}>
	{@render children?.()}
</div>
